BlogFodder.App/Pages/Shared/Components/EditorPluginCss/EditorPluginCssViewComponent.cs
using BlogFodder.Core;
using BlogFodder.Core.Plugins;
using BlogFodder.Core.Plugins.Interfaces;
using BlogFodder.Core.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace BlogFodder.App.Pages.Shared.Components.EditorPluginCss;

/// <summary>
/// Article block view component
/// </summary>
[ViewComponent(Name = "EditorPluginCss")]
public class EditorPluginCssViewComponent : ViewComponent
{
    private readonly ExtensionManager _extensionManager;
    private readonly BlogFodderSettings _optionsSnapshot;

    public EditorPluginCssViewComponent(ExtensionManager extensionManager, IOptions<BlogFodderSettings> optionsSnapshot)
    {
        _extensionManager = extensionManager;
        _optionsSnapshot = optionsSnapshot.Value;
    }

    public IViewComponentResult Invoke()
    {
        var cssFiles = new List<string>();
        var editorPlugins = _extensionManager.GetInstances<IEditorPlugin>(true);
        var plugins = _extensionManager.GetInstances<IPlugin>(true);
        var currentUrl = HttpContext.Request.Path.Value;
        var startsWithAdmin =
            currentUrl?.StartsWith(Constants.BackOffice.BackOfficeUrlDenoter, StringComparison.OrdinalIgnoreCase) ??
            false;

        // TODO - need to think about plugins that use CSS isolation, can use the following to add the styles
        /*foreach (var plugin in plugins)
        {
            var assembly = plugin.Value.GetType().Assembly;
            cssFiles.Add($"{assembly.GetName().Name}.styles.css");
        }
        foreach (var plugin in editorPlugins)
        {
            var assembly = plugin.Value.GetType().Assembly;
            cssFiles.Add($"{assembly.GetName().Name}.styles.css");
        }*/

        if (startsWithAdmin)
        {
            // TODO - Should these be in the appSettings?
            // Add mud blazor files
            cssFiles.Add("https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap");
            cssFiles.Add("_content/MudBlazor/MudBlazor.min.css");
            
            foreach (var plugin in editorPlugins)
            {
                if (plugin.Value.Editor?.CssFiles != null)
                {
                    foreach (var cssFile in plugin.Value.Editor.CssFiles)
                    {
                        cssFiles.Add(cssFile);
                    }
                }
            }
            foreach (var plugin in plugins)
            {
                if (plugin.Value.Editor?.CssFiles != null)
                {
                    foreach (var cssFile in plugin.Value.Editor.CssFiles)
                    {
                        cssFiles.Add(cssFile);
                    }
                }
            }
        }
        else
        {
            cssFiles.AddRange(_optionsSnapshot.FrontEnd.Styles);
            foreach (var plugin in editorPlugins)
            {
                if (plugin.Value.Content?.CssFiles != null)
                {
                    foreach (var cssFile in plugin.Value.Content.CssFiles)
                    {
                        cssFiles.Add(cssFile);
                    }
                }
            }
            foreach (var plugin in plugins)
            {
                var pluginCssFiles = plugin.Value.Content?.SelectMany(x => x.CssFiles);
                if (pluginCssFiles != null)
                {
                    foreach (var cssFile in pluginCssFiles)
                    {
                        cssFiles.Add(cssFile);
                    }
                }
            }
        }
        
        // Distinct to stop and duplicates
        // Should really be better checking than this
        return View(cssFiles.Distinct().ToList());
    }
}

BlogFodder.App/Pages/Shared/Components/EditorPluginJs/EditorPluginJsViewComponent.cs
using BlogFodder.Core;
using BlogFodder.Core.Plugins;
using BlogFodder.Core.Plugins.Interfaces;
using BlogFodder.Core.Settings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace BlogFodder.App.Pages.Shared.Components.EditorPluginJs;

/// <summary>
/// Article block view component
/// </summary>
[ViewComponent(Name = "EditorPluginJs")]
public class EditorPluginJsViewComponent : ViewComponent
{
    private readonly ExtensionManager _extensionManager;
    private readonly BlogFodderSettings _optionsSnapshot;
    public EditorPluginJsViewComponent(ExtensionManager extensionManager, IOptions<BlogFodderSettings> optionsSnapshot)
    {
        _extensionManager = extensionManager;
        _optionsSnapshot = optionsSnapshot.Value;
    }

    public IViewComponentResult Invoke()
    {
        var plugins = _extensionManager.GetInstances<IEditorPlugin>(true);

        var currentUrl = HttpContext.Request.Path.Value;
        var startsWithAdmin =
            currentUrl?.StartsWith(Constants.BackOffice.BackOfficeUrlDenoter, StringComparison.OrdinalIgnoreCase) ??
            false;
        var jsFiles = new List<string>();

        // Filter the content based on the URL
        if (startsWithAdmin)
        {
            // TODO - Should these be in the appSettings?
            // Add mud blazor files
            jsFiles.Add("_content/MudBlazor/MudBlazor.min.js");

            foreach (var plugin in plugins)
            {
                if (plugin.Value.Editor?.JsFiles != null)
                {
                    foreach (var jsFile in plugin.Value.Editor.JsFiles)
                    {
                        jsFiles.Add(jsFile);
                    }
                }
            }
        }
        else
        {
            jsFiles.AddRange(_optionsSnapshot.FrontEnd.Scripts);
            foreach (var plugin in plugins)
            {
                if (plugin.Value.Content?.JsFiles != null)
                {
                    foreach (var jsFile in plugin.Value.Content.JsFiles)
                    {
                        jsFiles.Add(jsFile);
                    }
                }
            }
        }

        // Distinct to stop and duplicates
        // Should really be better checking than this
        return View(jsFiles.Distinct().ToList());
    }
}

BlogFodder.App/Pages/Shared/_Layout.cshtml
@using BlogFodder.Core.Settings
@using Microsoft.Extensions.Options
@inject IOptions<BlogFodderSettings> Settings;
@{
    var mainSettings = Settings.Value;
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="~/"/>
    <link rel="icon" type="image/png" href="@mainSettings.Favicon"/>
    @await RenderSectionAsync("Head", false)
    <link rel="stylesheet" href="BlogFodder.App.styles.css" asp-append-version="true"/>
    @(await Component.InvokeAsync("EditorPluginCss"))
</head>
<body>
    @RenderBody()
    <script src="_framework/blazor.server.js"></script>
    <script>
        // Wait until a 'reload' button appears
        new MutationObserver((mutations, observer) => {
            if (document.querySelector('#components-reconnect-modal h5')) {
                // Now every 10 seconds, see if the server appears to be back, and if so, reload
                async function attemptReload() {
                    await fetch(''); // Check the server really is back
                    location.reload();
                }
                observer.disconnect();
                attemptReload();
                setInterval(attemptReload, 2000);
            }
        }).observe(document.body, { childList: true, subtree: true });
    </script>
    @await Component.InvokeAsync("EditorPluginJs")
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

BlogFodder.App/Pages/Shared/_ValidationScripts.cshtml
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.17.0/additional-methods.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/mvc/5.2.3/jquery.validate.unobtrusive.min.js"></script>